# Generated by Django 4.1.7 on 2023-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=455)),
                ('username', models.EmailField(max_length=643)),
                ('Password', models.CharField(max_length=78)),
                ('Re_password', models.CharField(max_length=78)),
            ],
        ),
    ]
