# Generated by Django 4.1.7 on 2023-03-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dell', '0002_rename_login_loginform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='First_Name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='username',
            field=models.EmailField(max_length=43),
        ),
    ]
