# Generated by Django 4.1.7 on 2023-03-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dell', '0003_alter_registrationform_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationform',
            old_name='Re_password',
            new_name='password1',
        ),
    ]
