# Generated by Django 4.1.7 on 2023-03-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dell', '0004_rename_re_password_registrationform_password1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.EmailField(max_length=90)),
                ('Password1', models.CharField(max_length=78)),
            ],
        ),
        migrations.DeleteModel(
            name='loginForm',
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='password1',
            field=models.CharField(max_length=78, null=True),
        ),
    ]
