# Generated by Django 4.1.7 on 2023-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dell', '0005_login_delete_loginform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='First_Name',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='Password',
            field=models.CharField(max_length=78, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='username',
            field=models.EmailField(max_length=43, null=True),
        ),
    ]
